name: Run JUnit Tests on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'

    - name: Extract classpath from .classpath file
      id: extract_classpath
      run: |
        classpath=$(grep -oP '(?<=<classpathentry kind="lib" path=").*(?="\/>)' .classpath | tr '\n' ':')
        echo "::set-output name=classpath::$classpath"

    - name: Compile tests
      run: javac -cp .:${{ steps.extract_classpath.outputs.classpath }} test/*.java

    - name: Run JUnit Tests
      run: java -cp .:${{ steps.extract_classpath.outputs.classpath }} org.junit.runner.JUnitCore $(find test -name "*.class" | sed 's/.class//' | tr / .)
